apiVersion: batch/v1
kind: Job
metadata:
  name: etoko-folio-job
spec:
  template:
    spec:
      containers:
      - name: etoko-folio-job
        image: yash5090/etoko-folio:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
