apiVersion: apps/v1
kind: Deployment
metadata:
  name: etoko-folio-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: etoko-folio
  template:
    metadata:
      labels:
        app: etoko-folio
    spec:
      containers:
        - name: etoko-folio
          image: yash5090/etoko-folio:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
